### PR TITLE
Temp

### PR DESCRIPTION
**Pull request by comminux**

### CODE REVIEW

**Comment by Nokius** [comment]
Hi @OhDaeto 

This is just a branch of the original project 
custodian/orn-warehouse

**Comment by comminux** [comment]
I am sorry. I have been studying the subject and accidentally called you. But you could not help with the error?

**Comment by Nokius** [comment]
sure I can try which issue

**Comment by comminux** [comment]
I compiled a fork from a temporary branch, but get the following error 
http://imgur.com/2XNHwFf

**Comment by Nokius** [comment]
is the compiling failing or the install ?

**Comment by comminux** [comment]
Failing after install. I use last version of SDK

**Comment by comminux** [comment]
Over the past year in the file there was no change
https://github.com/OhDaeto/harbour-warehouse/commits/master/qml/sailfish/main-sailfish.qml

**Comment by Nokius** [comment]
can u check 
rpm -qa | grep sailfishsilica-qt5

**Comment by comminux** [comment]
Mersdk - nothing
Emulator - sailfishsilica-qt5-0.21.54-10.69.1.jolla.i486
Jolla phone - sailfishsilica-qt5-0.21.54-10.69.1.jolla.armv7hl

**Comment by Nokius** [comment]
mh

**Comment by Nokius** [comment]
can us share the rpm?

**Comment by comminux** [comment]
Yes
https://openrepos.net/sites/default/files/packages/6214/harbour-warehouse-0.3-29.armv7hl.rpm or https://openrepos.net/content/lourens/warehouse-sailfishos-not-official-build

**Comment by Nokius** [comment]
I assume it's failing, cos cbcd253 and      63169c1 changed the spec file to build against OBS [build.merproject.org]

**Comment by comminux** [comment]
Well... Thank you very much! I will try build your fork and close pull request.

**Comment by Nokius** [comment]
@OhDaeto let me know if it will fail as well

**Comment by comminux** [comment]
I build from master branch and bump version on openrepos.net
http://imgur.com/GQ9AJbf

**Comment by Nokius** [comment]
What Version of SFOS u have on the Device?

**Comment by comminux** [comment]
2.0.0.10

**Comment by Nokius** [comment]
can u try devel-su pkcon install-local _rpm_

**Comment by comminux** [comment]
From local rpm package?

**Comment by Nokius** [comment]
can u ssu lr please

**Comment by comminux** [comment]
[Ssu lr.txt](https://github.com/Nokius/orn-warehouse/files/34727/Ssu.lr.txt)

**Comment by comminux** [comment]
Also log from Sailfish Emulator:
[nemo@SailfishEmul share]$ harbour-warehouse 
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL 
[W] unknown:85 - file:///usr/share/harbour-warehouse/qml/main-sailfish.qml:85:5: Syntax error 
         Component.onCompleted: {
         ^

**Comment by Nokius** [comment]
something is broken  _imho_

I never build warehouse myself 

atm u face a problem with glibc

**Comment by comminux** [comment]
So you never compiled a Warehouse from your source? Note emulator has a similar error with main-sailfish.qml:85:5

**Comment by Nokius** [comment]
may I did not 100% sure 

updating the SDK atm

**Comment by Nokius** [comment]
I just started the SDK with the project and I see Warning at this point :s

**Comment by comminux** [comment]
Come together to solve this problem on https://lists.sailfishos.org/cgi-bin/mailman/listinfo/devel

**Comment by comminux** [comment]
How do we write?

**Comment by Nokius** [comment]
join IRC (freenode) #sailfishos

**Pull request closed without merging**
